# https://docs.docker.com/engine/install/ubuntu/
- name: Uninstall old versions
  apt:
    name: "{{ docker_remove_packages }}"
    state: absent
- command: dpkg --print-architecture
  register: dpkg_architecture_result
  changed_when: no
- include_tasks: online.yml
  when: not docker_offline_install
- include_tasks: offline.yml
  when: docker_offline_install
- service:
    name: apparmor
    state: stopped
    enabled: false
  ignore_errors: yes
  notify: restart docker
- apt:
    name: apparmor
    state: absent
  notify: restart docker
- service:
    name: docker
    state: started
    enabled: yes
- template:
    src: docker-system-prune.j2
    dest: /etc/cron.daily/docker-system-prune
    mode: 0755
- name: Add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
