- name: Install using the apt repository | Set up the repository | 1. Update the apt package index and install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ docker_installation_prerequisite_packages }}"
    update_cache: yes
- file:
    path: "{{ docker_keyring_dir }}"
    mode: 0755
    state: directory
- name: Install using the apt repository | Set up the repository | 2. Add Docker’s official GPG key
  apt_key:
    url: "{{ docker_repository_key_url }}"
    keyring: "{{ docker_keyring_file }}"
- name: Install using the apt repository | Set up the repository | 3. Use the following command to set up the repository
  apt_repository:
    repo: "{{ docker_repository_source }}"
    filename: docker
- name: Install using the apt repository | Install Docker Engine
  block:
    - name: Update the apt package index and install Docker Engine, containerd, and Docker Compose
      apt:
        name: "{{ docker_packages }}"
        update_cache: yes