FROM {{ release_version_result.stdout }}
RUN apt-get remove {{ docker_remove_packages | join(' ')}} || true && \
    apt-get update && \
    apt-get install -y {{ docker_installation_prerequisite_packages | join (' ') }} && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL {{ docker_repository_key_url }} |  \
      gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo \
      "{{ docker_repository_source }}" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update
RUN mkdir -p /packages/deb && cd /packages/deb && apt-get download python3-pip {{ docker_packages | join(' ') }}
RUN apt-get install -y python3 python3-pip
RUN mkdir /packages/pip && pip download {{ docker_pip_packages | join(' ') }} -d /packages/pip